version: '3'
services:
  mysql:
    network_mode: host
    image: mysql:5.7
    container_name: db_marketplace
    restart: unless-stopped
    ports:
    - 3306:3306
#    command: --init-file /data/application/init.sql
    volumes:
    - ./bkp/mysql:/var/lib/mysql
    - ./:/var/www
#    - ./config/databases/scripts/init.sql:/data/application/init.sql
    env_file:
    - .env
  application:
    depends_on:
      - mysql
    image: marketplace
    container_name: marketplace
    build: .
    stdin_open: true
    tty: true
    ports:
    - 8000:80
