version: '3'
services:
  mysql:
    env_file:
      - ./docker/.env_mysql
    network_mode: host
    image: mysql:5.7
    container_name: db_marketplace
    restart: unless-stopped
    ports:
    - 3306:3306
    volumes:
    - ./../data-marketplace/:/var/lib/mysql
  application:
    depends_on:
      - mysql
    container_name: marketplace
    network_mode: host
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
    - 8000:8000
    volumes:
    - ./src/:/var/www
    command: "bash -c 'composer install;
                       cp /var/www/.env.example /var/www/.env;
                       php artisan key:generate;
                       php artisan migrate;
                       php artisan serve;
                     '"
